name: morty-stack

services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: maxtopor
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: morty_db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234